# This is a basic workflow to help you get started with Actions
h1 {
            font-size: 2em;
            font-weight: bold;
            margin-top: 20px;
        }

        .calendar-container {
            display: grid;
            grid-template-columns: repeat(5, 1fr); /* 5 cases par ligne */
            gap: 10px;
            padding: 20px;
            margin-top: 30px;
        }

        .calendar-box {
            width: 100%;
            height: 150px;
            background-color: #f5f5f5;
            border: 2px solid #ddd;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 2em;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .calendar-box:hover {
            background-color: #e0e0e0;
        }

        .calendar-box a {
            color: black;
            text-decoration: none;
        }

        .calendar-box:active {
            background-color: #d0d0d0;
        }

        .document-content {
            margin-top: 30px;
            font-size: 1.2em;
            padding: 20px;
        }
    </style>
</head>
<body>
    <h1>Calendrier de l'Avent</h1>
    <div class="calendar-container">
        <!-- Cases du calendrier -->
        <div class="calendar-box"><a href="#case1" onclick="openDocument('document1')">1</a></div>
        <div class="calendar-box"><a href="#case2" onclick="openDocument('document2')">2</a></div>
        <div class="calendar-box"><a href="#case3" onclick="openDocument('document3')">3</a></div>
        <div class="calendar-box"><a href="#case4" onclick="openDocument('document4')">4</a></div>
        <div class="calendar-box"><a href="#case5" onclick="openDocument('document5')">5</a></div>
        <div class="calendar-box"><a href="#case6" onclick="openDocument('document6')">6</a></div>
        <div class="calendar-box"><a href="#case7" onclick="openDocument('document7')">7</a></div>
        <div class="calendar-box"><a href="#case8" onclick="openDocument('document8')">8</a></div>
        <div class="calendar-box"><a href="#case9" onclick="openDocument('document9')">9</a></div>
        <div class="calendar-box"><a href="#case10" onclick="openDocument('document10')">10</a></div>
        <div class="calendar-box"><a href="#case11" onclick="openDocument('document11')">11</a></div>
        <div class="calendar-box"><a href="#case12" onclick="openDocument('document12')">12</a></div>
        <div class="calendar-box"><a href="#case13" onclick="openDocument('document13')">13</a></div>
        <div class="calendar-box"><a href="#case14" onclick="openDocument('document14')">14</a></div>
        <div class="calendar-box"><a href="#case15" onclick="openDocument('document15')">15</a></div>
        <div class="calendar-box"><a href="#case16" onclick="openDocument('document16')">16</a></div>
        <div class="calendar-box"><a href="#case17" onclick="openDocument('document17')">17</a></div>
        <div class="calendar-box"><a href="#case18" onclick="openDocument('document18')">18</a></div>
        <div class="calendar-box"><a href="#case19" onclick="openDocument('document19')">19</a></div>
        <div class="calendar-box"><a href="#case20" onclick="openDocument('document20')">20</a></div>
        <div class="calendar-box"><a href="#case21" onclick="openDocument('document21')">21</a></div>
        <div class="calendar-box"><a href="#case22" onclick="openDocument('document22')">22</a></div>
        <div class="calendar-box"><a href="#case23" onclick="openDocument('document23')">23</a></div>
        <div class="calendar-box"><a href="#case24" onclick="openDocument('document24')">24</a></div>
        <div class="calendar-box"><a href="#case25" onclick="openDocument('document25')">25</a></div>
    </div>

    <!-- Contenu des documents (à afficher lors de l'ouverture d'une case) -->
    <div class="document-content" id="documentContent">
        <p>Veuillez cliquer sur une case pour découvrir un document !</p>
    </div>

    <script>
        // Fonction pour ouvrir le contenu du document
        function openDocument(docId) {
            const content = {
                document1: "Contenu du document 1",
                document2: "Contenu du document 2",
                document3: "Contenu du document 3",
                document4: "Contenu du document 4",
                document5: "Contenu du document 5",
                document6: "Contenu du document 6",
                document7: "Contenu du document 7",
                document8: "Contenu du document 8",
                document9: "Contenu du document 9",
                document10: "Contenu du document 10",
                document11: "Contenu du document 11",
                document12: "Contenu du document 12",
                document13: "Contenu du document 13",
                document14: "Contenu du document 14",
                document15: "Contenu du document 15",
                document16: "Contenu du document 16",
                document17: "Contenu du document 17",
                document18: "Contenu du document 18",
                document19: "Contenu du document 19",
                document20: "Contenu du document 20",
                document21: "Contenu du document 21",
                document22: "Contenu du document 22",
                document23: "Contenu du document 23",
                document24: "Contenu du document 24",
                document25: "Contenu du document 25"
            };
            document.getElementById("documentContent").innerHTML = "<p>" + content[docId] + "</p>";
        }
    </script>
</body>
</html>
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
